### ISSUE TITLE
Autodeploy on github pages

### ISSUE THREAD

**Issue by dibericky** [mia-platform/api-explorer#60]
## The feauture or bug you are proposing
Autodeploy on github-pages when commit on master

## The description of the bug or the rationale of your proposal
When is made a commit on master, should be triggered a pipeline that makes a build and deploy it on github-pages.

## A snippet of code for replicating the issue or showing the proposal usage if applicable
Should be made something similar to [this with create-react-app](https://medium.com/@cmichel/how-to-deploy-a-create-react-app-with-github-actions-5e01f7a7b6b)

Example (untested):
```
name: Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Bootstrap packages
      run: npm run boot
    - name: Build page
      run: npm run build
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./build
```
## The expected result for your feature
Some minute after a merge of a pull-request, the feature/fix is visible on [Github Pages](https://mia-platform.github.io/api-explorer/)
